#7687
HeorhiiBoliuk/Drupal10Bootcamp pull request #40
Opened 2024-03-12 13:27 UTC by HeorhiiBoliuk

Add an opportunity to select a city of Ukraine and paste your API key in block configuration. Errors that server can pass are displayed in logs.

2024-03-12 13:41 UTC, KuzyaWkk commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +        \Drupal::logger('weather_block')->error('Failed to get weather data for city @city: @message', [
It is better to use Dependency Injection and create a container for services

2024-03-12 13:43 UTC, KuzyaWkk requested changes
Add .css and .svg files in module directory. Use Dependency Injection

2024-03-12 15:11 UTC, HeorhiiBoliuk commented
in the last commit deleted a useless rows

2024-03-12 15:36 UTC, lavrenchuk-dev approved these changes

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +    $this->logger = $logger;
Better to use constructor promotion https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.promotion
It is just simpler

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +   * Container for WeatherBlock.
Doesn't really make sense, what container? Block doesn't accept Container with services itself.
You could just use inherited, and parent also describes what this functions is for

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +      '#options' => array_combine($cities, $cities),
not like that is very important, but keys should be machine names, so in English without spaces, etc.
That said these strings should also be in English and wrapped with ->t(), and if you want them in Ukrainian, then translate them using Drupal's translation system.

Translating is not that straightforward, so you could leave it like that.

Also, I don't know if API accepts English names, if not then it is fine.

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +    $form['API - key'] = [
use "machine name" naming for form keys.

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +    if (empty($api_key)) {
#required => TRUE on the textfield element should cover that validation.

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +      $this->configuration['key'] = $api_key;
changing the configuration in the validate function doesn't sound good.

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +        $response = \Drupal::httpClient()->get($url);
Use dependency injection for httpClient

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +    return $this->configFactory->get('weather_block.settings')->get('cities');
I don't see wether_block.settings config, and is this function even used?

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +  private function getDefaultApiKey(): array {
Same as getDefaultCities

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/weather_block.info.yml
> +libraries:
I'm not even sure modules do anything with `libraries` configuration in info.yml

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/weather_block.module
> +  $attachments['#attached']['library'][] = 'weather_block/weather_block-css';
You can do that in build function of your block

2024-03-12 15:36 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/weather_block.schema.yml
> +      label: 'Weather Block'
If you are not willing to provide the correct schema of configuration, then do not create it (the schema.yml) at all.
It is not required

2024-03-12 15:37 UTC, lavrenchuk-dev requested changes
Approved my mistake, see comments above for requested changes

2024-03-13 08:05 UTC, KuzyaWkk commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +      $form_state->setErrorByName('settings][key', $this->t('Api Key can not be empty'));
I don't know if it works that way

2024-03-13 08:14 UTC, KuzyaWkk approved these changes

2024-03-13 08:38 UTC, lavrenchuk-dev requested changes
A 2 little notes, feel free to merge and close the task after fix

2024-03-13 08:38 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +    $build['#attached']['library'][] = 'weather_block/weather_block-css';
FYI, nothing prevents you to leave 
```
return [
...
'#attached' => ...
]
```

2024-03-13 08:38 UTC, lavrenchuk-dev commented on web/modules/custom/weather_block/src/Plugin/Block/WeatherBlock.php
> +      $form['settings']['key']['#default_value'] = $this->configuration['key'];
`'#default_value' => $this->configuration['key'] ?? NULL`
directly in the array above

2024-03-13 09:07 UTC, merged