#7744
HeorhiiBoliuk/Drupal10Bootcamp pull request #46
Opened 2024-03-25 08:37 UTC by HeorhiiBoliuk

Created a drush command that changes text format for article on basic html, and hook_post_update_NAME that changes text format on limited HTML.

2024-03-25 08:49 UTC, lavrenchuk-dev commented
> sfjodsof

dsfdsf

2024-03-25 08:57 UTC, ivandudardb approved these changes
LGTM

2024-03-26 07:28 UTC, lavrenchuk-dev requested changes

2024-03-26 07:28 UTC, lavrenchuk-dev commented on web/modules/custom/batch_api_drush/src/Commands/BatchApiDrushCommands.php
> + * of the services file to use.
Not sure about this comment

2024-03-26 07:28 UTC, lavrenchuk-dev commented on web/modules/custom/batch_api_drush/src/Commands/BatchApiDrushCommands.php
> +  public function getNodes(): int|array {
Does this need to be UNION type?

2024-03-26 07:28 UTC, lavrenchuk-dev commented on web/modules/custom/batch_api_drush/src/Commands/BatchApiDrushCommands.php
> +      ->execute();
The whole purpose of batch API in that case is to not try to load all entities.
Let's imagine you have 1 million entities that need to be updated in any way
You'll never be able to load all of them at once

2024-03-26 07:28 UTC, lavrenchuk-dev commented on web/modules/custom/batch_limited_html/batch_limited_html.post_update.php
> +  return Node::loadMultiple($nids);
The whole purpose of batch API in that case is to not try to load all entities.
Let's imagine you have 1 million entities that need to be updated in any way
You'll never be able to load all of them at once

2024-03-26 11:59 UTC, lavrenchuk-dev approved these changes

2024-03-26 11:59 UTC, merged