Task#7814.main
HeorhiiBoliuk/Drupal10Bootcamp pull request #50
Opened 2024-04-04 11:55 UTC by HeorhiiBoliuk

Created a custom block return in build function markup with custom text from config page. Add to configuration form of the block a field with link to editing a content of block. Use in this block a tokens. Added a new global config - social links. Where user can input a custom label for social links menu. This label using in menu template like a variable. Cached a block using config page tag.
Added some configs after installation a multilingual modules.

2024-04-04 12:02 UTC, ivandudardb approved these changes
LGTM

2024-04-04 12:19 UTC, andriy-tkachuk commented
Commit messages should be clearer. For example:

2024-04-04 12:24 UTC, andriy-tkachuk commented on web/modules/custom/copyrights_block/src/Plugin/Block/BlockCopyrightBlock.php
> +    $copyright_text = $this->token->replace($token_text);
???

2024-04-04 12:24 UTC, andriy-tkachuk commented on web/themes/custom/my_awesome_theme/templates/menu/menu--extras--social-network--footer.html.twig
> +  {{ social_label }}
if empty?

2024-04-04 12:24 UTC, andriy-tkachuk commented on web/modules/custom/copyrights_block/copyrights_block.module
> +function copyrights_block_preprocess_menu(&$variables) {
Move to theme

2024-04-04 13:29 UTC, andriy-tkachuk requested changes

2024-04-04 13:29 UTC, andriy-tkachuk commented on web/themes/custom/my_awesome_theme/templates/menu/menu--extras--social-network--footer.html.twig
> +{% if (social_label != 0) %}
Why?

2024-04-12 09:23 UTC, lavrenchuk-dev requested changes

2024-04-12 09:23 UTC, lavrenchuk-dev commented on web/modules/custom/copyrights_block/src/Plugin/Block/BlockCopyrightBlock.php
> +      '#markup' => 'Copyrights text can be edited <a href="http://my-site.ddev.site/admin/structure/config_pages">here</a>',
translation?
P.S. the link itself shouldn't be translatable

2024-04-12 09:23 UTC, lavrenchuk-dev commented on web/modules/custom/copyrights_block/src/Plugin/Block/BlockCopyrightBlock.php
> +      return [''];
You are losing caches here.
Once block renders when $config page is missing, it will stay cached even after you'll add global configurations

2024-04-12 09:23 UTC, lavrenchuk-dev commented on web/themes/custom/my_awesome_theme/templates/menu/menu--extras--social-network--footer.html.twig
> +{% if (social_label) %}
unnecessary brackets, but whatever.
Also this check is not enough, if global configuration exist, but field is empty you will render empty h2 tag

2024-04-15 06:08 UTC, lavrenchuk-dev requested changes

2024-04-15 06:08 UTC, lavrenchuk-dev commented on web/themes/custom/my_awesome_theme/templates/menu/menu--extras--social-network--footer.html.twig
> +{% if social_label is not empty %}
is social_label empty if the field is empty? (spoiler: it is not)

2024-04-15 06:08 UTC, lavrenchuk-dev commented on web/modules/custom/copyrights_block/src/Plugin/Block/BlockCopyrightBlock.php
> +        '#markup' => 'No copyrights found',
t

2024-04-22 07:28 UTC, lavrenchuk-dev approved these changes
Feel free to merge after fixing conflicts

2024-04-22 09:07 UTC, merged